### ISSUE TITLE
pseudorank

### ISSUE THREAD

**Issue by chatchavan** [journalovi/2024-tsandilas-ranktransforms#4]
It seems that the `pseudorank` package is [not on CRAN](https://github.com/happma/pseudorank). Could you add to the code somewhere to install it from the Github repo with `devtools::install_github("happma/pseudorank")`?

**Comment by ephanis** [comment]
@chatchavan This package is only used in np.anova.R  (downloaded from here: From http://www.uni-koeln.de/~luepsen/R/). We call it in our experimental code that evaluates Lüpsen's generalizations of nonparametric tests but only with the default parameter `pseudo=F`. So normally, the library is not required: `if (pseudo) library(pseudorank)`

Do our scripts give an error?

**Comment by chatchavan** [comment]
**How I found this out:** I tried to compile the whole project using Quarto in Rstudio. There were several packages missing on my computer here and there, so I searched all occurances of for `library(` and batch-installed them.

**Suggestion:** Perhaps you can add a comment next to the line that calls `library(pseudorank)`? At least this comment will indicate which package it is (just in case there's a different package with the same name on CRAN in the future.

Note: This is an optional suggestion as I just try helping Lonni figure out the compilation process. I haven't checked which parts of the repo is relevant (or not) to the main claims in the paper.

**Comment by ephanis** [comment]
I added comments to np.anova.R as suggested.

**Comment by chatchavan** [comment]
Thanks!
