### ISSUE TITLE
Missing data files in Siestrup-and-Schubotz-23

### ISSUE THREAD

**Issue by chatchavan** [journalovi/2024-tsandilas-ranktransforms#5]
In the supplementary material `Siestrup-and-Schubotz-23`, several `.csv` files were referred to, but t they are absent from the folder.

**Comment by ephanis** [comment]
@chatchavan This dataset is not publicly available but the authors have included a [data availability statement](https://direct.mit.edu/jocn/article/35/11/1823/117477/Minor-Changes-Change-Memories-Functional-Magnetic#4359305): *"The data sets generated for this study are available on request to the corresponding author."* We asked the authors and they provided the data, but we don't have a permission to share them online.

**Comment by ephanis** [comment]
@chatchavan Explanations were added [here](https://github.com/journalovi/2024-tsandilas-ranktransforms/tree/main/supplementary/examples-case-studies/6-Case-studies) as well within the [R Markdown document ](https://www.journalovi.org/2024-tsandilas-ranktransforms/supplementary/examples-case-studies/6-Case-studies/Siestrup-and-Schubotz-23/Siestrup-and-Schubotz-23.html)that presents the analysis of the study.

I also corrected the links both in the article and the supplementary material, as they were pointing to the original github repository.

**Comment by chatchavan** [comment]
Got it. Great!
